//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JinderAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int ChatMessageId { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
    
        public virtual JinderUser JinderUser { get; set; }
        public virtual JinderUser JinderUser1 { get; set; }
    }
}
