//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JinderAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpressionLog
    {
        public int ExpressionLogId { get; set; }
        public Nullable<int> SourceUserId { get; set; }
        public Nullable<int> TargetUserId { get; set; }
        public Nullable<bool> IsInterested { get; set; }
        public Nullable<System.DateTime> ExpressionDate { get; set; }
    
        public virtual JinderUser JinderUser { get; set; }
        public virtual JinderUser JinderUser1 { get; set; }
    }
}
